# Generated by Django 5.2.1 on 2025-06-26 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_diacompletado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Describe los detalles de la tarea', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='diaCompletado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='task',
            name='f_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importante',
            field=models.BooleanField(default=False, verbose_name='¿Es importante?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='titulo',
            field=models.CharField(help_text='Ingresa un título breve para la tarea', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
