# Generated by Django 4.2 on 2025-09-25 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_suscripcionpush'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='equipo',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='equipo_id',
            field=models.IntegerField(default=0, verbose_name='ID del equipo en API'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='equipo_nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_suscripcion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
