# Generated by Django 4.2 on 2025-09-28 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_remove_suscripcion_equipo_suscripcion_equipo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.CharField(max_length=50)),
                ('equipo_nombre', models.CharField(max_length=100)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
