# Generated by Django 4.2 on 2025-09-28 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_suscripcionequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcionpush',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.AlterUniqueTogether(
            name='suscripcion',
            unique_together={('usuario', 'equipo_id')},
        ),
        migrations.DeleteModel(
            name='SuscripcionEquipo',
        ),
        migrations.DeleteModel(
            name='SuscripcionPush',
        ),
    ]
