# Generated by Django 5.2.11 on 2026-02-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_suscripcionpush_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
