# Generated by Django 3.2.25 on 2026-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_delete_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaBalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_balon', models.CharField(max_length=50)),
                ('causa', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('foto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporta', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=20)),
                ('tipo_objeto', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrendaRopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('condicion', models.CharField(default='Óptimo', max_length=20)),
                ('detalle_defecto', models.TextField(blank=True, null=True)),
                ('nombre_apartado', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=20)),
                ('objeto', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Entrega',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
