# Generated by Django 3.2.25 on 2026-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20260303_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajabalon',
            name='alquilado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='curso_apartado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='devuelto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='evento_apartado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='fecha_uso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prendaropa',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
