# Generated by Django 3.2.25 on 2026-05-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20260313_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=20)),
                ('pago', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('extra', 'Extra'), ('grave', 'Grave')], default='normal', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(blank=True, max_length=50)),
                ('evento', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_uso', models.DateField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='cantidad_apartada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prendaropa',
            name='dias_alquiler',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ReservaPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tasks.prendaropa')),
            ],
        ),
    ]
