# Generated by Django 3.2.25 on 2026-05-05 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20260505_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaalimento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='asistenciaalimento',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='asistenciaalimento',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='asistenciaalimento',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='asistenciaalimento',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='asistenciaalimento',
            name='fecha_uso',
        ),
        migrations.AddField(
            model_name='reservaprenda',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservaprenda',
            name='curso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservaprenda',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservaprenda',
            name='evento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
    model_name='reservaprenda',
    name='fecha_reserva',
    field=models.DateTimeField(default=django.utils.timezone.now),
    preserve_default=False,
),
       migrations.AddField(
    model_name='reservaprenda',
    name='fecha_uso',
    field=models.DateField(default=django.utils.timezone.now),
),
        migrations.AddField(
    model_name='reservaprenda',
    name='nombre',
    field=models.CharField(default='Sin nombre', max_length=100),
),
    ]
