# Generated by Django 3.2.25 on 2026-05-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20260505_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prendaropa',
            name='curso_apartado',
        ),
        migrations.RemoveField(
            model_name='prendaropa',
            name='dias_alquiler',
        ),
        migrations.RemoveField(
            model_name='prendaropa',
            name='evento_apartado',
        ),
        migrations.RemoveField(
            model_name='prendaropa',
            name='fecha_uso',
        ),
        migrations.RemoveField(
            model_name='prendaropa',
            name='nombre_apartado',
        ),
        migrations.AlterField(
            model_name='reservaprenda',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservaprenda',
            name='fecha_uso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaprenda',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
