# Generated by Django 3.2.25 on 2026-05-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20260512_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=20)),
                ('objeto', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
