# Generated by Django 3.2.25 on 2026-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_historialentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=100, unique=True)),
                ('uid_nfc', models.CharField(blank=True, max_length=255, null=True)),
                ('entregado_hoy', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
