# Generated by Django 3.2.25 on 2026-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_usuariocomedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('datos', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
