# Generated by Django 3.2.25 on 2026-05-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalonNFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_balon', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('codigo_nfc', models.CharField(max_length=100, unique=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
