# Generated by Django 3.2.25 on 2026-05-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_solicitudobjeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('col', models.IntegerField()),
                ('profesor', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('salon', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='clase', max_length=30)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='tasks.horariocurso')),
            ],
        ),
    ]
