# Generated by Django 3.2.25 on 2026-05-29 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0021_logsistema_mensajechat_notificacion_perfil_salachat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ultima_conexion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_real',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_apartar_prendas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
