# Generated by Django 3.2.25 on 2026-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20260528_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroentrega',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Entrega', 'verbose_name_plural': 'Registros de Entrega'},
        ),
        migrations.AddField(
            model_name='registroentrega',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroentrega',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
