# Generated by Django 3.2.25 on 2026-06-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20260529_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalonInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(max_length=50, unique=True, verbose_name='ID o Código del Balón')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca o Identificador')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo (Ej: Balón Fútbol)')),
                ('estado', models.CharField(default='Excelente', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
