# Generated by Django 3.2.25 on 2026-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_baloninventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroentrega',
            options={},
        ),
        migrations.AddField(
            model_name='registroentrega',
            name='id_prestamo_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Copia Texto Plano'),
        ),
    ]
